### ISSUE TITLE
Gem name matches existing gem on rubygems.org

### ISSUE THREAD

**Issue by majormoses** [sensu-plugins/sensu-plugins-nrpe#2]
https://rubygems.org/gems/sensu-plugins-nrpe

@scosist @mattyjones how do we want to handle that?

**Comment by majormoses** [comment]
Hoping we can transfer the ownership.

**Comment by scosist** [comment]
I can add another owner to the gem. What's the email address for the Sensu_Plugins profile on rubygems?

**Comment by majormoses** [comment]
Ya to be honest I really only have access to repos and only became a maintainer recently. So I am not sure but my guess might be this: https://github.com/sensu-plugins/sensu-plugins-nrpe/blob/master/travis.yml#L14

**Comment by scosist** [comment]
Good guess. Sensu_Plugins is now an owner.
